### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by LinSky0323**
老師好，我是陳聖鎧，我來交2-1作業
http://13.114.168.77:8000/api/mrts
http://13.114.168.77:8000/api/attraction/10
http://13.114.168.77:8000/api/attraction/100
http://13.114.168.77:8000/api/attractions?page=2
http://13.114.168.77:8000/api/attractions?page=1&keyword=北
http://13.114.168.77:8000/api/attractions?page=0&keyword=新北投

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://13.114.168.77:8000/api/mrts is incorrect.
2. We should not get all the data and do pagination by our own code (how about 1,000,000 rows?). We should use database feature to do pagination directly.

**Comment by LinSky0323** [comment]
老師好，我是陳聖鎧，我對mrts的api做了修改，請你確認看看
http://13.114.168.77:8000/api/mrts

**Comment by cwpeng** [comment]
We should not get all the data and do pagination by our own code (how about 1,000,000 rows?). We should use database feature to do pagination directly.

**Comment by LinSky0323** [comment]
老師好，我是陳聖鎧，我把拿檔案的事盡量都利用sql語句處理，不會再將資料庫裡的資料都拿出來了，再麻煩老師確認了，謝謝

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should not get all the data and do pagination by our own code (how about 1,000,000 rows?). We should use database feature to do pagination directly.

`session.query(Attraction)` get all data from database, `[12*page:12*page+12]` do pagination in your own code. `session.query(Attraction).filter(Attraction.mrt == keyword)` will transfer to SQL with where clause and executing, so it used SQL feature to do filtering.

You have to know what SQLAlchemy actually do for you. Use programming package without solid basic knowledge will not make things great.

**Comment by LinSky0323** [comment]
老師對不起：
我覺得我的英文理解能力不太到位，我不太確定老師說的問題是哪裡，我大概知道我拿資料的方式不太OK，可能要從資料庫或是SQL語句上做改變，但是我沒有很看懂第二段老師是講什麼問題
我有查SQL的運作順序，我了解的應該是用select時會先拿from的資料A，在對A做where篩選出要的資料B，在做分組group_by得資料C，這時候從c裡拿出select要的東西(*就是把C全收下)D，limit是把最後的資料做選取範圍呈現而已。
所以我用limit的方式只是把D的資料取12比出來而已，還是會有取所有的資料(D)的部份，所以不對，是這樣子嗎

**Comment by LinSky0323** [comment]
老師好，我是陳聖鎧，我做了點修改：
1把[1,12]這種寫法改成limit.offset了
2.把mrt加個index
3.修改是不是最後一頁的邏輯 之前寫的還要連一次SQL有點笨
麻煩老師確認了

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
